/**
 * Sudoku pure logic: a 9x9 board. A complete solution is generated by
 * randomized backtracking, then a symmetric set of cells is removed to form
 * the puzzle (always solvable: the original solution remains valid). The
 * player fills cells 1-9 (or clears them); conflicts are flagged, and the
 * game is won when every cell is filled with no conflicts. A game clock runs
 * until the win. Deterministic functions over a plain state object.
 */

export const SIZE = 9

export interface SudokuState {
  /** The fixed clue cells (null = free to edit). */
  puzzle: (number | null)[][]
  /** The current player grid (clues + entries). */
  grid: (number | null)[][]
  /** Seconds elapsed since the puzzle started (frozen on win). */
  elapsed: number
  won: boolean
  rng: () => number
}

/** Puzzle difficulties: clue counts. */
export const DIFFICULTIES = { easy: 45, normal: 35, hard: 30 } as const
export type Difficulty = keyof typeof DIFFICULTIES

function shuffle<T>(arr: T[], rng: () => number): T[] {
  for (let i = arr.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1))
    const tmp = arr[i]!
    arr[i] = arr[j]!
    arr[j] = tmp
  }
  return arr
}

function emptyGrid(): (number | null)[][] {
  return Array.from({ length: SIZE }, () => Array<number | null>(SIZE).fill(null))
}

function valid(grid: (number | null)[][], r: number, c: number, n: number): boolean {
  for (let i = 0; i < SIZE; i += 1) {
    if (grid[r]![i] === n || grid[i]![c] === n) return false
  }
  const br = Math.floor(r / 3) * 3
  const bc = Math.floor(c / 3) * 3
  for (let dr = 0; dr < 3; dr += 1) {
    for (let dc = 0; dc < 3; dc += 1) {
      if (grid[br + dr]![bc + dc] === n) return false
    }
  }
  return true
}

/** Fill the grid by randomized backtracking; returns whether it succeeded. */
function fill(grid: (number | null)[][], rng: () => number): boolean {
  for (let r = 0; r < SIZE; r += 1) {
    for (let c = 0; c < SIZE; c += 1) {
      if (grid[r]![c] === null) {
        const candidates = shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9], rng)
        for (const n of candidates) {
          if (valid(grid, r, c, n)) {
            grid[r]![c] = n
            if (fill(grid, rng)) return true
            grid[r]![c] = null
          }
        }
        return false
      }
    }
  }
  return true
}

/** A complete, valid solution. */
export function generateSolution(rng: () => number): (number | null)[][] {
  const grid = emptyGrid()
  if (!fill(grid, rng)) throw new Error('dsh-minigames: sudoku generator failed')
  return grid
}

/** Remove cells symmetrically down to (at most) `givens` clues. */
export function makePuzzle(solution: (number | null)[][], givens: number, rng: () => number): (number | null)[][] {
  const puzzle = solution.map(row => [...row])
  const order = shuffle(
    Array.from({ length: SIZE * SIZE }, (_, i) => [Math.floor(i / SIZE), i % SIZE] as [number, number]),
    rng,
  )
  let remaining = SIZE * SIZE
  for (const [r, c] of order) {
    if (remaining <= givens) break
    if (puzzle[r]![c] === null) continue
    const r2 = SIZE - 1 - r
    const c2 = SIZE - 1 - c
    if (puzzle[r2]![c2] === null) continue
    // Never drop below the target; symmetric pairs keep the puzzle solvable.
    const removed = r === r2 && c === c2 ? 1 : 2
    if (remaining - removed < givens) continue
    puzzle[r]![c] = null
    puzzle[r2]![c2] = null
    remaining -= removed
  }
  return puzzle
}

/** A fresh puzzle at the given difficulty. */
export function createSudokuState(rng: () => number = Math.random, difficulty: Difficulty = 'normal'): SudokuState {
  const puzzle = makePuzzle(generateSolution(rng), DIFFICULTIES[difficulty], rng)
  return { puzzle, grid: puzzle.map(row => [...row]), elapsed: 0, won: false, rng }
}

/** Advance the game clock (only before the win). */
export function tick(state: SudokuState, dt: number): void {
  if (!state.won) state.elapsed += dt
}

/** Whether the number at (r, c) conflicts with its row, column or box. */
export function conflictsAt(state: SudokuState, r: number, c: number): boolean {
  const n = state.grid[r]![c]
  if (n === null) return false
  for (let i = 0; i < SIZE; i += 1) {
    if (i !== c && state.grid[r]![i] === n) return true
    if (i !== r && state.grid[i]![c] === n) return true
  }
  const br = Math.floor(r / 3) * 3
  const bc = Math.floor(c / 3) * 3
  for (let dr = 0; dr < 3; dr += 1) {
    for (let dc = 0; dc < 3; dc += 1) {
      const rr = br + dr
      const cc = bc + dc
      if ((rr !== r || cc !== c) && state.grid[rr]![cc] === n) return true
    }
  }
  return false
}

/**
 * Fill (n 1-9) or clear (n 0) a free cell. Fixed clues are never editable.
 * Returns false for invalid input or a locked cell.
 */
export function place(state: SudokuState, r: number, c: number, n: number): boolean {
  if (state.won || r < 0 || r >= SIZE || c < 0 || c >= SIZE) return false
  if (state.puzzle[r]![c] !== null) return false
  if (n < 0 || n > 9) return false
  if (n === 0) {
    state.grid[r]![c] = null
    return true
  }
  state.grid[r]![c] = n
  // Won when every cell is filled and no cell conflicts.
  if (state.grid.every(row => row.every(cell => cell !== null)) && !hasConflicts(state)) {
    state.won = true
  }
  return true
}

/** Whether any cell on the board currently conflicts. */
export function hasConflicts(state: SudokuState): boolean {
  for (let r = 0; r < SIZE; r += 1) {
    for (let c = 0; c < SIZE; c += 1) {
      if (conflictsAt(state, r, c)) return true
    }
  }
  return false
}
