/**
 * Sudoku pure logic: a 9x9 board. A complete solution is generated by
 * randomized backtracking, then a symmetric set of cells is removed to form
 * the puzzle (always solvable: the original solution remains valid). The
 * player fills cells 1-9 (or clears them); conflicts are flagged, and the
 * game is won when every cell is filled with no conflicts. A game clock runs
 * until the win. Deterministic functions over a plain state object.
 */
export declare const SIZE = 9;
export interface SudokuState {
    /** The fixed clue cells (null = free to edit). */
    puzzle: (number | null)[][];
    /** The current player grid (clues + entries). */
    grid: (number | null)[][];
    /** Seconds elapsed since the puzzle started (frozen on win). */
    elapsed: number;
    won: boolean;
    rng: () => number;
}
/** Puzzle difficulties: clue counts. */
export declare const DIFFICULTIES: {
    readonly easy: 45;
    readonly normal: 35;
    readonly hard: 30;
};
export type Difficulty = keyof typeof DIFFICULTIES;
/** A complete, valid solution. */
export declare function generateSolution(rng: () => number): (number | null)[][];
/** Remove cells symmetrically down to (at most) `givens` clues. */
export declare function makePuzzle(solution: (number | null)[][], givens: number, rng: () => number): (number | null)[][];
/** A fresh puzzle at the given difficulty. */
export declare function createSudokuState(rng?: () => number, difficulty?: Difficulty): SudokuState;
/** Advance the game clock (only before the win). */
export declare function tick(state: SudokuState, dt: number): void;
/** Whether the number at (r, c) conflicts with its row, column or box. */
export declare function conflictsAt(state: SudokuState, r: number, c: number): boolean;
/**
 * Fill (n 1-9) or clear (n 0) a free cell. Fixed clues are never editable.
 * Returns false for invalid input or a locked cell.
 */
export declare function place(state: SudokuState, r: number, c: number, n: number): boolean;
/** Whether any cell on the board currently conflicts. */
export declare function hasConflicts(state: SudokuState): boolean;
